# config.yaml
train_filename: "train.csv"
test_filename:  "test.csv"

data:
  basepath:        "../dataset"
  image_directory: "images"

labels:
  classes: ["1", "2", "3", "4", "5", "6", "7", "8", "9",
            "10", "11", "13", "14", "15", "16", "17", "18", "19"]
  names: ["person",        # 1
        "bicycle",         # 2
        "car",             # 3
        "motorcycle",      # 4
        "airplane",        # 5
        "bus",             # 6
        "train",           # 7
        "truck",           # 8
        "boat",            # 9
        "traffic light",   # 10
        "fire hydrant",    # 11
        "stop sign",       # 13  
        "parking meter",   # 14
        "bench",           # 15
        "bird",            # 16
        "cat",             # 17
        "dog",             # 18
        "horse"]           # 19
  num_of_labels: 18          # ← length of the list above

image:
  resized_size: 320          # pixels (square: 320 × 320)
